import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from "@/components/header"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Frosina Cvetkovska',
  // description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-violet-50 text-gray-950`}>
        <Header/>
        {children}
        </body>
    </html>
  )
}
